# Generated by Django 4.2.3 on 2023-09-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_turno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='disponible',
        ),
    ]
