# Generated by Django 4.2.3 on 2023-08-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_rename_productos_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutosVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
                ('kilometraje', models.BigIntegerField()),
                ('precio', models.BigIntegerField()),
            ],
        ),
    ]
