# Generated by Django 4.2.3 on 2023-08-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_autosventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosventa',
            name='kilometraje',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='autosventa',
            name='precio',
            field=models.PositiveBigIntegerField(),
        ),
    ]
