# Generated by Django 4.2.3 on 2023-08-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_autosventa_kilometraje_alter_autosventa_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mecanico',
            old_name='especilidad',
            new_name='especialidad',
        ),
    ]
